### ISSUE TITLE
Chatbot không đọc được tin nhắn của người ngoài

### ISSUE THREAD

**Issue by LeMinhQuoc** [misonomikadev/ChatGPTFacebookPage#3]
- Chatbot chỉ nhận tin nhắn của chủ tài khoản fanpage.
- Những người khác nhắn vào sẽ không trả lời. 
ở đây mình console.log cái input của handler nhá :
![image](https://user-images.githubusercontent.com/54875792/230427607-09e1e9fa-a113-41cc-848e-26ffce17c515.png)

**Comment by eptprofile** [comment]
Vì app của bạn phải có quyền messages được verify với facebook và để app ở live mode
Nếu bạn muốn để người khác dùng đc mà app bạn vẫn đang trong development mode thì bạn có thể thêm người đó là tester trong setting của app nhé :>

**Comment by LeMinhQuoc** [comment]
làm sao đổi nhỉ ?

**Comment by LeMinhQuoc** [comment]
![image](https://user-images.githubusercontent.com/54875792/230526459-d22260e9-6b95-4d3a-a8b7-67aa6174d6b4.png)
đổi như này à, nhưng đổi rồi vẫn y như cũ á.
